titleOnly: true
scopes:
  - sdk
  - mcp
  - os
  - abstractions
  - identity
  - server
  - api
  - security
  - deps
  - ci
  - docs
  - tests
  - aws
  - db
types:
  - feat
  - fix
  - docs
  - style
  - refactor
  - perf
  - test
  - build
  - ci
  - chore
  - revert