name: AWS Projects CI

on:
  push:
    branches: [ main ]
    paths:
      - 'src/aws/**'
      - 'tests/Avro.Aws.*/**'
      - '.github/workflows/aws-ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/aws/**'
      - 'tests/Avro.Aws.*/**'
      - '.github/workflows/aws-ci.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.100-rc.1.25451.107'
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration Release
      
    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal src/aws/*/Avro.Aws.*.csproj tests/Avro.Aws.*/Avro.Aws.*.UnitTests.csproj

  package:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.100-rc.1.25451.107'
        
    - name: Pack
      run: |
        dotnet pack src/aws/Avro.Aws.Abstractions/Avro.Aws.Abstractions.csproj -c Release --no-build --output nupkgs
        dotnet pack src/aws/Avro.Aws.Auth/Avro.Aws.Auth.csproj -c Release --no-build --output nupkgs
        
    - name: Push to NuGet
      run: dotnet nuget push "nupkgs/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json