name: AWS Projects CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ main ]
    paths:
      - 'src/aws/**'
      - 'tests/Avro.Aws.*/**'
      - '.github/workflows/aws-ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/aws/**'
      - 'tests/Avro.Aws.*/**'
      - '.github/workflows/aws-ci.yml'

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.100-rc.1.25451.107'
        
    - name: Clear NuGet cache
      run: dotnet nuget locals all --clear

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration Release
      
    - name: Test
      run: |
        dotnet test tests/Avro.Aws.Abstractions.UnitTests/Avro.Aws.Abstractions.UnitTests.csproj --no-build --configuration Release --verbosity normal
        dotnet test tests/Avro.Aws.Auth.UnitTests/Avro.Aws.Auth.UnitTests.csproj --no-build --configuration Release --verbosity normal

  package:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: read
      packages: write
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.100-rc.1.25451.107'
        
    - name: Pack
      run: |
        dotnet pack src/aws/Avro.Aws.Abstractions/Avro.Aws.Abstractions.csproj -c Release --output nupkgs
        dotnet pack src/aws/Avro.Aws.Auth/Avro.Aws.Auth.csproj -c Release --output nupkgs
        
    - name: Push to NuGet
      run: dotnet nuget push "nupkgs/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json