name: 'Lint PR'

on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - uses: amannn/action-semantic-pull-request@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Configure types based on your existing commit patterns
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            chore
            ci
            deps
            deps-dev
            docker
          # Require scope for better organization
          requireScope: false
          # Custom subject pattern (optional)
          subjectPattern: ^(?![A-Z]).+$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            didn't match the configured pattern. Please ensure that the subject
            doesn't start with an uppercase character.
          # Validate against these scopes (optional)
          scopes: |
            sdk
            mcp
            os
            abstractions
            identity
            server
            api
            security
            deps
            ci
            docs
            tests
          # Don't require scope but validate if present
          validateSingleCommit: false
          ignoreLabels: |
            ignore-semantic-pull-request