name: MCP Flow

on:
  push:
    branches: [ main ]
    paths:
      - 'src/mcp/**'
      - '.github/workflows/mcp-pipeline.yml'
      - 'tests/Avro.Mcp.*.UnitTests/**'
      - 'tests/Avro.Mcp.*.IntegrationTests/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/mcp/**'
      - '.github/workflows/mcp-pipeline.yml'
      - 'tests/Avro.Mcp.*.UnitTests/**'
      - 'tests/Avro.Mcp.*.IntegrationTests/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '10.0.x'
        dotnet-quality: 'preview'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Upload MCP server artifact
      uses: actions/upload-artifact@v4
      with:
        name: mcp-server-artifacts
        path: |
          **/bin/Release/net10.0/Avro.Mcp.Example*
          **/bin/Release/Avro.Mcp.*.nupkg

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'
        dotnet-quality: 'preview'

    - name: Restore dependencies
      run: dotnet restore

    - name: Run Unit Tests
      run: dotnet test --filter "FullyQualifiedName~Avro.Mcp" --configuration Release --verbosity normal --logger trx

    - name: Run Integration Tests
      run: dotnet test --filter "FullyQualifiedName~Avro.Mcp.Example.IntegrationTests" --configuration Release --verbosity normal --logger trx

  deploy:
    needs: test
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'
        dotnet-quality: 'preview'

    - name: Pack NuGet packages
      run: dotnet pack src/mcp/Avro.Mcp.Example --configuration Release --output ./nupkg

    - name: Push NuGet packages
      run: |
        dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}